# Generated by Django 4.1.7 on 2023-03-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_follow_posts_follow_prevent_self_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='posts_follow_prevent_self_follow',
        ),
    ]
